/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedRepoIdRouteImport } from './routes/_authenticated/$repoId'
import { Route as AuthenticatedFindRouteImport } from './routes/_authenticated/find'
import { Route as AuthenticatedRepoIdBranchesRouteImport } from './routes/_authenticated/$repoId_.branches'
import { Route as AuthenticatedRepoIdCommitsRouteImport } from './routes/_authenticated/$repoId_.commits'
import { Route as AuthenticatedRepoIdTagsRouteImport } from './routes/_authenticated/$repoId_.tags'
import { Route as AuthenticatedCommitShaRouteImport } from './routes/_authenticated/commit/$sha'
import { Route as AuthenticatedRepoIdCommitShaRouteImport } from './routes/_authenticated/$repoId_.commit.$sha'
import { Route as AuthenticatedBlobRefSplatRouteImport } from './routes/_authenticated/blob/$ref/$'
import { Route as AuthenticatedTreeRefSplatRouteImport } from './routes/_authenticated/tree/$ref/$'
import { Route as AuthenticatedRepoIdBlobRefSplatRouteImport } from './routes/_authenticated/$repoId_.blob.$ref.$'
import { Route as AuthenticatedRepoIdTreeRefSplatRouteImport } from './routes/_authenticated/$repoId_.tree.$ref.$'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepoIdRoute = AuthenticatedRepoIdRouteImport.update({
  id: '/$repoId',
  path: '/$repoId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFindRoute = AuthenticatedFindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepoIdBranchesRoute =
  AuthenticatedRepoIdBranchesRouteImport.update({
    id: '/$repoId_/branches',
    path: '/$repoId/branches',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRepoIdCommitsRoute =
  AuthenticatedRepoIdCommitsRouteImport.update({
    id: '/$repoId_/commits',
    path: '/$repoId/commits',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRepoIdTagsRoute = AuthenticatedRepoIdTagsRouteImport.update({
  id: '/$repoId_/tags',
  path: '/$repoId/tags',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommitShaRoute = AuthenticatedCommitShaRouteImport.update({
  id: '/commit/$sha',
  path: '/commit/$sha',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepoIdCommitShaRoute =
  AuthenticatedRepoIdCommitShaRouteImport.update({
    id: '/$repoId_/commit/$sha',
    path: '/$repoId/commit/$sha',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBlobRefSplatRoute =
  AuthenticatedBlobRefSplatRouteImport.update({
    id: '/blob/$ref/$',
    path: '/blob/$ref/$',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTreeRefSplatRoute =
  AuthenticatedTreeRefSplatRouteImport.update({
    id: '/tree/$ref/$',
    path: '/tree/$ref/$',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRepoIdBlobRefSplatRoute =
  AuthenticatedRepoIdBlobRefSplatRouteImport.update({
    id: '/$repoId_/blob/$ref/$',
    path: '/$repoId/blob/$ref/$',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRepoIdTreeRefSplatRoute =
  AuthenticatedRepoIdTreeRefSplatRouteImport.update({
    id: '/$repoId_/tree/$ref/$',
    path: '/$repoId/tree/$ref/$',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/500': typeof errors500Route
  '/$repoId': typeof AuthenticatedRepoIdRoute
  '/find': typeof AuthenticatedFindRoute
  '/$repoId/branches': typeof AuthenticatedRepoIdBranchesRoute
  '/$repoId/commits': typeof AuthenticatedRepoIdCommitsRoute
  '/$repoId/tags': typeof AuthenticatedRepoIdTagsRoute
  '/commit/$sha': typeof AuthenticatedCommitShaRoute
  '/$repoId/commit/$sha': typeof AuthenticatedRepoIdCommitShaRoute
  '/blob/$ref/$': typeof AuthenticatedBlobRefSplatRoute
  '/tree/$ref/$': typeof AuthenticatedTreeRefSplatRoute
  '/$repoId/blob/$ref/$': typeof AuthenticatedRepoIdBlobRefSplatRoute
  '/$repoId/tree/$ref/$': typeof AuthenticatedRepoIdTreeRefSplatRoute
}
export interface FileRoutesByTo {
  '/500': typeof errors500Route
  '/$repoId': typeof AuthenticatedRepoIdRoute
  '/find': typeof AuthenticatedFindRoute
  '/': typeof AuthenticatedIndexRoute
  '/$repoId/branches': typeof AuthenticatedRepoIdBranchesRoute
  '/$repoId/commits': typeof AuthenticatedRepoIdCommitsRoute
  '/$repoId/tags': typeof AuthenticatedRepoIdTagsRoute
  '/commit/$sha': typeof AuthenticatedCommitShaRoute
  '/$repoId/commit/$sha': typeof AuthenticatedRepoIdCommitShaRoute
  '/blob/$ref/$': typeof AuthenticatedBlobRefSplatRoute
  '/tree/$ref/$': typeof AuthenticatedTreeRefSplatRoute
  '/$repoId/blob/$ref/$': typeof AuthenticatedRepoIdBlobRefSplatRoute
  '/$repoId/tree/$ref/$': typeof AuthenticatedRepoIdTreeRefSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(errors)/500': typeof errors500Route
  '/_authenticated/$repoId': typeof AuthenticatedRepoIdRoute
  '/_authenticated/find': typeof AuthenticatedFindRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/$repoId_/branches': typeof AuthenticatedRepoIdBranchesRoute
  '/_authenticated/$repoId_/commits': typeof AuthenticatedRepoIdCommitsRoute
  '/_authenticated/$repoId_/tags': typeof AuthenticatedRepoIdTagsRoute
  '/_authenticated/commit/$sha': typeof AuthenticatedCommitShaRoute
  '/_authenticated/$repoId_/commit/$sha': typeof AuthenticatedRepoIdCommitShaRoute
  '/_authenticated/blob/$ref/$': typeof AuthenticatedBlobRefSplatRoute
  '/_authenticated/tree/$ref/$': typeof AuthenticatedTreeRefSplatRoute
  '/_authenticated/$repoId_/blob/$ref/$': typeof AuthenticatedRepoIdBlobRefSplatRoute
  '/_authenticated/$repoId_/tree/$ref/$': typeof AuthenticatedRepoIdTreeRefSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/500'
    | '/$repoId'
    | '/find'
    | '/$repoId/branches'
    | '/$repoId/commits'
    | '/$repoId/tags'
    | '/commit/$sha'
    | '/$repoId/commit/$sha'
    | '/blob/$ref/$'
    | '/tree/$ref/$'
    | '/$repoId/blob/$ref/$'
    | '/$repoId/tree/$ref/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/500'
    | '/$repoId'
    | '/find'
    | '/'
    | '/$repoId/branches'
    | '/$repoId/commits'
    | '/$repoId/tags'
    | '/commit/$sha'
    | '/$repoId/commit/$sha'
    | '/blob/$ref/$'
    | '/tree/$ref/$'
    | '/$repoId/blob/$ref/$'
    | '/$repoId/tree/$ref/$'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(errors)/500'
    | '/_authenticated/$repoId'
    | '/_authenticated/find'
    | '/_authenticated/'
    | '/_authenticated/$repoId_/branches'
    | '/_authenticated/$repoId_/commits'
    | '/_authenticated/$repoId_/tags'
    | '/_authenticated/commit/$sha'
    | '/_authenticated/$repoId_/commit/$sha'
    | '/_authenticated/blob/$ref/$'
    | '/_authenticated/tree/$ref/$'
    | '/_authenticated/$repoId_/blob/$ref/$'
    | '/_authenticated/$repoId_/tree/$ref/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  errors500Route: typeof errors500Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$repoId': {
      id: '/_authenticated/$repoId'
      path: '/$repoId'
      fullPath: '/$repoId'
      preLoaderRoute: typeof AuthenticatedRepoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/find': {
      id: '/_authenticated/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof AuthenticatedFindRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$repoId_/branches': {
      id: '/_authenticated/$repoId_/branches'
      path: '/$repoId/branches'
      fullPath: '/$repoId/branches'
      preLoaderRoute: typeof AuthenticatedRepoIdBranchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$repoId_/commits': {
      id: '/_authenticated/$repoId_/commits'
      path: '/$repoId/commits'
      fullPath: '/$repoId/commits'
      preLoaderRoute: typeof AuthenticatedRepoIdCommitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$repoId_/tags': {
      id: '/_authenticated/$repoId_/tags'
      path: '/$repoId/tags'
      fullPath: '/$repoId/tags'
      preLoaderRoute: typeof AuthenticatedRepoIdTagsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commit/$sha': {
      id: '/_authenticated/commit/$sha'
      path: '/commit/$sha'
      fullPath: '/commit/$sha'
      preLoaderRoute: typeof AuthenticatedCommitShaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$repoId_/commit/$sha': {
      id: '/_authenticated/$repoId_/commit/$sha'
      path: '/$repoId/commit/$sha'
      fullPath: '/$repoId/commit/$sha'
      preLoaderRoute: typeof AuthenticatedRepoIdCommitShaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blob/$ref/$': {
      id: '/_authenticated/blob/$ref/$'
      path: '/blob/$ref/$'
      fullPath: '/blob/$ref/$'
      preLoaderRoute: typeof AuthenticatedBlobRefSplatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tree/$ref/$': {
      id: '/_authenticated/tree/$ref/$'
      path: '/tree/$ref/$'
      fullPath: '/tree/$ref/$'
      preLoaderRoute: typeof AuthenticatedTreeRefSplatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$repoId_/blob/$ref/$': {
      id: '/_authenticated/$repoId_/blob/$ref/$'
      path: '/$repoId/blob/$ref/$'
      fullPath: '/$repoId/blob/$ref/$'
      preLoaderRoute: typeof AuthenticatedRepoIdBlobRefSplatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$repoId_/tree/$ref/$': {
      id: '/_authenticated/$repoId_/tree/$ref/$'
      path: '/$repoId/tree/$ref/$'
      fullPath: '/$repoId/tree/$ref/$'
      preLoaderRoute: typeof AuthenticatedRepoIdTreeRefSplatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedRepoIdRoute: typeof AuthenticatedRepoIdRoute
  AuthenticatedFindRoute: typeof AuthenticatedFindRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedRepoIdBranchesRoute: typeof AuthenticatedRepoIdBranchesRoute
  AuthenticatedRepoIdCommitsRoute: typeof AuthenticatedRepoIdCommitsRoute
  AuthenticatedRepoIdTagsRoute: typeof AuthenticatedRepoIdTagsRoute
  AuthenticatedCommitShaRoute: typeof AuthenticatedCommitShaRoute
  AuthenticatedRepoIdCommitShaRoute: typeof AuthenticatedRepoIdCommitShaRoute
  AuthenticatedBlobRefSplatRoute: typeof AuthenticatedBlobRefSplatRoute
  AuthenticatedTreeRefSplatRoute: typeof AuthenticatedTreeRefSplatRoute
  AuthenticatedRepoIdBlobRefSplatRoute: typeof AuthenticatedRepoIdBlobRefSplatRoute
  AuthenticatedRepoIdTreeRefSplatRoute: typeof AuthenticatedRepoIdTreeRefSplatRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedRepoIdRoute: AuthenticatedRepoIdRoute,
  AuthenticatedFindRoute: AuthenticatedFindRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedRepoIdBranchesRoute: AuthenticatedRepoIdBranchesRoute,
  AuthenticatedRepoIdCommitsRoute: AuthenticatedRepoIdCommitsRoute,
  AuthenticatedRepoIdTagsRoute: AuthenticatedRepoIdTagsRoute,
  AuthenticatedCommitShaRoute: AuthenticatedCommitShaRoute,
  AuthenticatedRepoIdCommitShaRoute: AuthenticatedRepoIdCommitShaRoute,
  AuthenticatedBlobRefSplatRoute: AuthenticatedBlobRefSplatRoute,
  AuthenticatedTreeRefSplatRoute: AuthenticatedTreeRefSplatRoute,
  AuthenticatedRepoIdBlobRefSplatRoute: AuthenticatedRepoIdBlobRefSplatRoute,
  AuthenticatedRepoIdTreeRefSplatRoute: AuthenticatedRepoIdTreeRefSplatRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  errors500Route: errors500Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
